version: 0.2
env:
  secrets-manager:
    TOKEN: firstSecret:tokenForSonar
phases:
  install:
    runtime-versions:
      java: latest
      nodejs: 14
    commands:
      - npm install -g jest
  build:
    commands:
      - npm test
      - mvn sonar:sonar -Dsonar.projectKey=leesungon -Dsonar.organization=leesungon -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$TOKEN
